baseURL: 'https://blog.rikdewit.nl'
languageCode: 'en-us'
title: 'Rik de Wit'
theme: 'PaperMod'



params:
    defaultTheme: auto
    editPost:
        URL: "https://github.com/rikdewit/personal-blog-rikdewit/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    ShowReadingTime: true
    homeInfoParams:
        Title: My blog experiment
        Content: >
         Here I will share my projects and thoughts.  
        
         If you would like to contact me\: rikdewit1997@gmail.com

    socialIcons:
        - name: github
          url: "https://github.com/rikdewit"
        - name: buymeacoffee
          url: "https://www.buymeacoffee.com/rikdewit"
        - name: instagram
          url: "https://instagram.com/woesnos"
        - name: rss
          url: "/index.xml"

    author: Rik
    disableScrollToTop: false
    comments: true
    # comments_css: "css/comments.css"


menu:
    main:
        - identifier: categories
          name: Archive
          url: /archive/
          weight: 10
assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"